# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-13 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='avail',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='rental',
            name='reserve',
            field=models.DateTimeField(blank=True),
        ),
    ]
