# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-13 21:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_auto_20171213_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='reserve',
            field=models.BooleanField(default=False),
        ),
    ]
